# Generated by Django 6.0.1 on 2026-02-01 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=300, unique=True)),
                ("name", models.CharField(max_length=300, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("smart_meter", "smart_meter"),
                            ("smart_thermo", "smart_thermo"),
                            ("sensor", "sensor"),
                        ]
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="NetworkReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("metric_name", models.CharField(blank=True, max_length=500)),
                ("metric_value", models.FloatField(default=0)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading",
                        to="readings.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
