# Generated by Django 6.0.1 on 2026-02-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("readings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="device",
            table="devices",
        ),
        migrations.AlterModelTable(
            name="networkreading",
            table="device_readings",
        ),
    ]
